// tablas_lista.js
module.exports = [
  // ---- Proyecto 1: Campo / Insumos / Labores (supabaseCampo) ----
  { local: 'local_0_unidades_negocio', remoto: '0_unidades_negocio', proyecto: 'campo' },
  { local: 'local_1_ciclo_contable', remoto: '1_ciclo_contable', proyecto: 'campo' },
  { local: 'local_c_consumos_combustibles', remoto: 'c_consumos_combustibles', proyecto: 'campo' },
  { local: 'local_ctb_movimientos_cc', remoto: 'ctb_movimientos_cc', proyecto: 'campo' },
  { local: 'local_i_insumos_catalogo', remoto: 'i_insumos_catalogo', proyecto: 'campo' },
  { local: 'local_i_insumos_detalle', remoto: 'i_insumos_detalle', proyecto: 'campo' },
  { local: 'local_i_insumos_movimientos', remoto: 'i_insumos_movimientos', proyecto: 'campo' },
  { local: 'local_i_insumos_ordenes_Compra', remoto: 'i_insumos_ordenes_Compra', proyecto: 'campo' },
  { local: 'local_i_insumos_rubros', remoto: 'i_insumos_rubros', proyecto: 'campo' },
  { local: 'local_i_insumos_subrubros', remoto: 'i_insumos_subrubros', proyecto: 'campo' },
  { local: 'local_i_insumosingresos', remoto: 'i_insumosingresos', proyecto: 'campo' },
  { local: 'local_m_labores_maquinaria', remoto: 'm_labores_maquinaria', proyecto: 'campo' },
  { local: 'local_p_aplicacionesOrdenes', remoto: 'p_aplicacionesOrdenes', proyecto: 'campo' },
  { local: 'local_p_centroCostos', remoto: 'p_centroCostos', proyecto: 'campo' },
  { local: 'local_p_labores_valorizado', remoto: 'p_labores_valorizado', proyecto: 'campo' },
  { local: 'local_p_macro_labores', remoto: 'p_macro_labores', proyecto: 'campo' },
  { local: 'local_p_personal_historial', remoto: 'p_personal_historial', proyecto: 'campo' },
  { local: 'local_p_normas_conducta', remoto: 'p_normas_conducta', proyecto: 'campo' },
  { local: 'local_p_proveedores', remoto: 'p_proveedores', proyecto: 'campo' },
  { local: 'local_p_recetas_aplicaciones', remoto: 'p_recetas_aplicaciones', proyecto: 'campo' },
  { local: 'local_p_tipo_control_aplicaciones', remoto: 'p_tipo_control_aplicaciones', proyecto: 'campo' },
  { local: 'local_par_depositos', remoto: 'par_depositos', proyecto: 'campo' },
  { local: 'local_par_maquinaria_herramientas', remoto: 'par_maquinaria_herramientas', proyecto: 'campo' },
  { local: 'local_r_aplicaciones_fol_fert', remoto: 'r_aplicaciones_fol_fert', proyecto: 'campo' },
  { local: 'local_r_campo_riego', remoto: 'r_campo_riego', proyecto: 'campo' },
  { local: 'local_r_jornada_trabajo', remoto: 'r_jornada_trabajo', proyecto: 'campo' },
  { local: 'local_r_mantenimiento_maquinaria', remoto: 'r_mantenimiento_maquinaria', proyecto: 'campo' },
  { local: 'local_p_personal_sanciones', remoto: 'p_personal_sanciones', proyecto: 'campo' },
  { local: 'local_sys_permisos_usuario', remoto: 'sys_permisos_usuario', proyecto: 'campo' },
  
  // ---- Proyecto 2: Cosecha y Logística (supabaseCosecha) ----
  { local: 'local_ciclos_cosecha', remoto: 'ciclos_cosecha', proyecto: 'cosecha' },
  { local: 'local_config_descargas', remoto: 'config_descargas', proyecto: 'cosecha' },
  { local: 'local_cosecha', remoto: 'cosecha', proyecto: 'cosecha' },
  { local: 'local_descarte', remoto: 'descarte', proyecto: 'cosecha' },
  { local: 'local_despachos_produccion', remoto: 'despachos_produccion', proyecto: 'cosecha' },
  { local: 'local_detalle_recepcion', remoto: 'detalle_recepcion', proyecto: 'cosecha' },
  { local: 'local_p_calibre', remoto: 'p_calibre', proyecto: 'cosecha' },
  { local: 'local_p_categoria', remoto: 'p_categoria', proyecto: 'cosecha' },
  { local: 'local_p_clientes', remoto: 'p_clientes', proyecto: 'cosecha' },
  { local: 'local_p_cuadros', remoto: 'p_cuadros', proyecto: 'cosecha' },
  { local: 'local_p_cultivo', remoto: 'p_cultivo', proyecto: 'cosecha' },
  { local: 'local_p_embalaje', remoto: 'p_embalaje', proyecto: 'cosecha' },
  { local: 'local_p_inventario_plantacion', remoto: 'p_inventario_plantacion', proyecto: 'cosecha' },
  { local: 'local_p_marcos_plantacion', remoto: 'p_marcos_plantacion', proyecto: 'cosecha' },
  { local: 'local_p_nomina_personal', remoto: 'p_nomina_personal', proyecto: 'cosecha' },
  { local: 'local_p_legajo_datos', remoto: 'p_legajo_datos', proyecto: 'cosecha' },
  { local: 'local_p_productores', remoto: 'p_productores', proyecto: 'cosecha' },
  { local: 'local_p_tipo_pallet', remoto: 'p_tipo_pallet', proyecto: 'cosecha' },
  { local: 'local_p_variedades', remoto: 'p_variedades', proyecto: 'cosecha' },
  { local: 'local_paletizado', remoto: 'paletizado', proyecto: 'cosecha' },
  { local: 'local_recepcion', remoto: 'recepcion', proyecto: 'cosecha' }
];